version: "3.8"

services:
  api:
    image: chien314832001/hw5_api:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: appdb
      DATABASE_HOST: db
      DATABASE_NAME: appdb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_URL: postgresql://postgres:password@db:5432/appdb
    networks:
      - appnet

  web:
    image: chien314832001/hw5_web:latest
    ports:
      - "80:80"
    networks:
      - appnet
    depends_on:
      - api
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname != isl3080
      restart_policy:
        condition: on-failure

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb

    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - appnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == db
      restart_policy:
        condition: on-failure

networks:
  appnet:
    driver: overlay

volumes:
  dbdata: {}



