apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: hw6
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # This PVC is intended to bind to a hostPath PersistentVolume on the lab node.
  # Use the `manual` storage class to bind to the statically-created PV below.
  storageClassName: manual
