apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    app: hw6
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # Directory on the lab node that will store Postgres data. Ensure this path exists on the lab node.
    path: /var/lib/hw6-postgres
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - db
