name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch slash command
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commands: |
            spectify
            paln
            tasks
            implement
          reaction: rocket
